name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.7'
    - name: Go Version
      run: "go version"
    - name: Run Tests
      run: "go test -v -race -coverprofile=coverage.txt -covermode=atomic ./..."
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.txt
        flags: golang-core
        fail_ci_if_error: true
